### ISSUE TITLE
Feature request: option to exclude headings through a global setting

### ISSUE THREAD

**Issue by PKDmeDEV** [iLiftALot/insta-toc#2]
Hi,

I know there is an option to exclude any heading by specifying it in the script. In my notes I always want to start from H2. I never want H1 in TOC, as H1 is the note's title, and sections only start from H2. Could you add an option to disable it globally? It could be an opt-in feature to use H1 for those who want it.

Thanks

**Comment by iLiftALot** [comment]
Yeah that's easy enough, I'll get that done now for you.
